import { User } from "../models/user.model";


export const userData: User[] = [
    {
        _id: 'u102',
        username: 'NoyLeibo',
        password: '123123',
        fullname: 'Noy Leibovich',
        imgUrl: 'https://res.cloudinary.com/dysh9q6ir/image/upload/v1706788350/%D7%9C%D7%9C%D7%90_%D7%A9%D7%9D_ngeib7.png',
        bio: '',
        following: [
            {
                _id: 'u107',
                fullname: 'Emily',
                username: 'EmilyC',
                imgUrl: '../../img/faces/emily.png',
            }
        ],
        followers: [
            {
                _id: 'u107',
                fullname: 'Emily',
                username: 'EmilyC',
                imgUrl: '../../img/faces/emily.png',
            },
        ],
        savedPostsIds: ['s102', 's105'],
    },
    {
        _id: 'u103',
        username: 'MichaelB',
        password: 'michael123',
        fullname: 'Michael Brown',
        imgUrl: '../../img/faces/michael.png',
        bio: '',
        following: [],
        followers: [
            {
                _id: 'u109',
                fullname: 'Alice',
                username: 'AliceM',
                imgUrl: '',
            },
        ],
        savedPostsIds: ['s103', 's106'],
    },
    {
        _id: 'u104',
        username: 'ChrisJ',
        password: 'chrispass',
        fullname: 'Chris Johnson',
        imgUrl: '',
        bio: '',
        following: [
            {
                _id: 'u110',
                fullname: 'Sarah',
                username: 'SarahK',
                imgUrl: '',
            },
        ],
        followers: [],
        savedPostsIds: ['s104'],
    },
    {
        _id: 'u105',
        username: 'LindaG',
        password: 'linda123',
        fullname: 'Linda Gates',
        imgUrl: '',
        bio: '',
        following: [
            {
                _id: 'u112',
                fullname: 'Kevin',
                username: 'KevinT',
                imgUrl: '../../img/faces/kevin.png',
            },
        ],
        followers: [],
        savedPostsIds: ['s105'],
    },
    {
        _id: 'u106',
        username: 'DavidL',
        password: 'davidpass',
        fullname: 'David Lee',
        imgUrl: '../../img/faces/david.png',
        bio: '',
        following: [
            {
                _id: 'u114',
                fullname: 'Emma',
                username: 'EmmaP',
                imgUrl: '../../img/faces/emma.png',
            },
        ],
        followers: [],
        savedPostsIds: ['s106'],
    },

    // Commenters and Likers
    {
        _id: 'u107',
        username: 'EmilyC',
        password: 'emilypass',
        fullname: 'Emily',
        imgUrl: '../../img/faces/emily.png',
        bio: '',
        following: [
            {
                _id: 'u102',
                username: 'AnnaS',
                fullname: 'Anna Smith',
                imgUrl: '../../img/faces/anna.png',
            },
        ],
        followers: [],
        savedPostsIds: ['s102'],
    },
    {
        _id: 'u108',
        username: 'JohnD',
        password: 'john123',
        fullname: 'John',
        imgUrl: '../../img/faces/john.png',
        bio: '',
        following: [],
        followers: [],
        savedPostsIds: ['s102', 's104'],
    },
    {
        _id: 'u109',
        username: 'AliceM',
        password: 'alice123',
        fullname: 'Alice',
        imgUrl: '../../img/faces/alice.png',
        bio: '',
        following: [],
        followers: [
            {
                _id: 'u103',
                fullname: 'Michael Brown',
                username: 'MichaelB',
                imgUrl: '../../img/faces/michael.png',
            },
        ],
        savedPostsIds: ['s103'],
    },
    {
        _id: 'u110',
        username: 'SarahK',
        password: 'sarahpass',
        fullname: 'Sarah',
        imgUrl: '../../img/faces/sarah.png',
        bio: '',
        following: [
            {
                _id: 'u104',
                fullname: 'Chris Johnson',
                username: 'ChrisJ',
                imgUrl: '../../img/faces/chris.png',
            },
        ],
        followers: [],
        savedPostsIds: ['s104', 's105'],
    },
    {
        _id: 'u111',
        username: 'MikeL',
        password: 'mikepass',
        fullname: 'Mike',
        imgUrl: '../../img/faces/mike.png',
        bio: '',
        following: [],
        followers: [],
        savedPostsIds: ['s104'],
    },
    {
        _id: 'u112',
        username: 'KevinT',
        password: 'kevinpass',
        fullname: 'Kevin',
        imgUrl: '../../img/faces/kevin.png',
        bio: '',
        following: [
            {
                _id: 'u105',
                fullname: 'Linda Gates',
                username: 'LindaG',
                imgUrl: '../../img/faces/linda.png',
            },
        ],
        followers: [],
        savedPostsIds: ['s105', 's106'],
    },
    {
        _id: 'u113',
        username: 'GraceW',
        password: 'grace123',
        fullname: 'Grace',
        imgUrl: '../../img/faces/grace.png',
        bio: '',
        following: [],
        followers: [],
        savedPostsIds: ['s105'],
    },
]
